---
- name: "Create new directory 'backend'"
  file:
    path: ~/backend
    state: directory

- name: "Move compressed backend Archive"
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend

- name: "Decompress backend Archive"
  unarchive:
    src: ~/backend/artifact.tar.gz
    dest: ~/backend
    remote_src: yes

- name: "Remove compressed Archive"
  file:
    path: ~/backend/artifact.tar.gz
    state: absent


- name: "Execute 'npm run build'"
  command: npm run build
  args:
    chdir: ~/backend

- name: "Start pm2 server"
  command: 
          pm2 start npm -- start
          pm2 logs
  args:
    chdir: ~/backend